development:
  facebook_app_id: '142951129148413'
  facebook_secret_key: 'ab9bb6972624b3f2ff3e09cce1cb062'
  callback_url: http://spider.dev:3000/auth/facebook/callback

test: &development

production:
  app_id: '12341234etcetcetc'
  secret_key: '123456788etcetcetc'
  callback_url: http://your_app_url.heroku.com/
