development: &defaults
  FB_APP_ID: '130690353713201'
  FB_APP_SECRET: 'd05642357fb03910f2c7d6f0b6708e89'
  FB_CALLBACK_URL: 'http://localhost:3000/auth/facebook/callback'

test: &development
  <<: *defaults  
